# Generated by Django 4.2.5 on 2023-09-08 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_balance', models.IntegerField()),
                ('fee_statement', models.FileField(upload_to='')),
                ('previous_term_report', models.FileField(upload_to='')),
                ('is_awarded', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('reasons', models.TextField(blank=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=100)),
                ('parents_name', models.CharField(max_length=100)),
                ('parents_phone', models.CharField(max_length=15)),
                ('parents_id', models.FileField(upload_to='')),
                ('school_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField()),
                ('year_of_completion', models.IntegerField()),
                ('disability_status', models.BooleanField(default=False)),
                ('family_status', models.CharField(choices=[('orphan', 'Orphan'), ('single parents', 'Single Parents'), ('both parents', 'Both Parents')], max_length=30)),
                ('death_certificate_father', models.FileField(upload_to='')),
                ('death_certificate_mother', models.FileField(upload_to='')),
                ('family_income', models.IntegerField()),
                ('applied_bursary_before', models.BooleanField()),
                ('annual_school_fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=10)),
                ('annual_fees', models.IntegerField()),
                ('fees_paid', models.IntegerField()),
                ('arreas', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.profile')),
            ],
        ),
    ]
