# Generated by Django 4.2.5 on 2023-09-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='death_certificate_father',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='death_certificate_mother',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
